// Generated by gencpp from file minnow/command_valResponse.msg
// DO NOT EDIT!


#ifndef MINNOW_MESSAGE_COMMAND_VALRESPONSE_H
#define MINNOW_MESSAGE_COMMAND_VALRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace minnow
{
template <class ContainerAllocator>
struct command_valResponse_
{
  typedef command_valResponse_<ContainerAllocator> Type;

  command_valResponse_()
    : retVal(0.0)  {
    }
  command_valResponse_(const ContainerAllocator& _alloc)
    : retVal(0.0)  {
    }



   typedef float _retVal_type;
  _retVal_type retVal;




  typedef boost::shared_ptr< ::minnow::command_valResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::minnow::command_valResponse_<ContainerAllocator> const> ConstPtr;

}; // struct command_valResponse_

typedef ::minnow::command_valResponse_<std::allocator<void> > command_valResponse;

typedef boost::shared_ptr< ::minnow::command_valResponse > command_valResponsePtr;
typedef boost::shared_ptr< ::minnow::command_valResponse const> command_valResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::minnow::command_valResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::minnow::command_valResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace minnow

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'minnow': ['/home/monica/panda_work/src/minnow_1_folder/minnow/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::minnow::command_valResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::minnow::command_valResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::minnow::command_valResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::minnow::command_valResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::minnow::command_valResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::minnow::command_valResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::minnow::command_valResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da3154dad63e349cf6f23ecf2e2ae03b";
  }

  static const char* value(const ::minnow::command_valResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda3154dad63e349cULL;
  static const uint64_t static_value2 = 0xf6f23ecf2e2ae03bULL;
};

template<class ContainerAllocator>
struct DataType< ::minnow::command_valResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "minnow/command_valResponse";
  }

  static const char* value(const ::minnow::command_valResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::minnow::command_valResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 retVal\n\
\n\
";
  }

  static const char* value(const ::minnow::command_valResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::minnow::command_valResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.retVal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct command_valResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::minnow::command_valResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::minnow::command_valResponse_<ContainerAllocator>& v)
  {
    s << indent << "retVal: ";
    Printer<float>::stream(s, indent + "  ", v.retVal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MINNOW_MESSAGE_COMMAND_VALRESPONSE_H
