// Generated by gencpp from file minnow/command_val.msg
// DO NOT EDIT!


#ifndef MINNOW_MESSAGE_COMMAND_VAL_H
#define MINNOW_MESSAGE_COMMAND_VAL_H

#include <ros/service_traits.h>


#include <minnow/command_valRequest.h>
#include <minnow/command_valResponse.h>


namespace minnow
{

struct command_val
{

typedef command_valRequest Request;
typedef command_valResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct command_val
} // namespace minnow


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::minnow::command_val > {
  static const char* value()
  {
    return "e20d6f99125da9e8135bd77ec2d0dabf";
  }

  static const char* value(const ::minnow::command_val&) { return value(); }
};

template<>
struct DataType< ::minnow::command_val > {
  static const char* value()
  {
    return "minnow/command_val";
  }

  static const char* value(const ::minnow::command_val&) { return value(); }
};


// service_traits::MD5Sum< ::minnow::command_valRequest> should match 
// service_traits::MD5Sum< ::minnow::command_val > 
template<>
struct MD5Sum< ::minnow::command_valRequest>
{
  static const char* value()
  {
    return MD5Sum< ::minnow::command_val >::value();
  }
  static const char* value(const ::minnow::command_valRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::minnow::command_valRequest> should match 
// service_traits::DataType< ::minnow::command_val > 
template<>
struct DataType< ::minnow::command_valRequest>
{
  static const char* value()
  {
    return DataType< ::minnow::command_val >::value();
  }
  static const char* value(const ::minnow::command_valRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::minnow::command_valResponse> should match 
// service_traits::MD5Sum< ::minnow::command_val > 
template<>
struct MD5Sum< ::minnow::command_valResponse>
{
  static const char* value()
  {
    return MD5Sum< ::minnow::command_val >::value();
  }
  static const char* value(const ::minnow::command_valResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::minnow::command_valResponse> should match 
// service_traits::DataType< ::minnow::command_val > 
template<>
struct DataType< ::minnow::command_valResponse>
{
  static const char* value()
  {
    return DataType< ::minnow::command_val >::value();
  }
  static const char* value(const ::minnow::command_valResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MINNOW_MESSAGE_COMMAND_VAL_H
