// Generated by gencpp from file minnow/throttle_val.msg
// DO NOT EDIT!


#ifndef MINNOW_MESSAGE_THROTTLE_VAL_H
#define MINNOW_MESSAGE_THROTTLE_VAL_H

#include <ros/service_traits.h>


#include <minnow/throttle_valRequest.h>
#include <minnow/throttle_valResponse.h>


namespace minnow
{

struct throttle_val
{

typedef throttle_valRequest Request;
typedef throttle_valResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct throttle_val
} // namespace minnow


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::minnow::throttle_val > {
  static const char* value()
  {
    return "e20d6f99125da9e8135bd77ec2d0dabf";
  }

  static const char* value(const ::minnow::throttle_val&) { return value(); }
};

template<>
struct DataType< ::minnow::throttle_val > {
  static const char* value()
  {
    return "minnow/throttle_val";
  }

  static const char* value(const ::minnow::throttle_val&) { return value(); }
};


// service_traits::MD5Sum< ::minnow::throttle_valRequest> should match 
// service_traits::MD5Sum< ::minnow::throttle_val > 
template<>
struct MD5Sum< ::minnow::throttle_valRequest>
{
  static const char* value()
  {
    return MD5Sum< ::minnow::throttle_val >::value();
  }
  static const char* value(const ::minnow::throttle_valRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::minnow::throttle_valRequest> should match 
// service_traits::DataType< ::minnow::throttle_val > 
template<>
struct DataType< ::minnow::throttle_valRequest>
{
  static const char* value()
  {
    return DataType< ::minnow::throttle_val >::value();
  }
  static const char* value(const ::minnow::throttle_valRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::minnow::throttle_valResponse> should match 
// service_traits::MD5Sum< ::minnow::throttle_val > 
template<>
struct MD5Sum< ::minnow::throttle_valResponse>
{
  static const char* value()
  {
    return MD5Sum< ::minnow::throttle_val >::value();
  }
  static const char* value(const ::minnow::throttle_valResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::minnow::throttle_valResponse> should match 
// service_traits::DataType< ::minnow::throttle_val > 
template<>
struct DataType< ::minnow::throttle_valResponse>
{
  static const char* value()
  {
    return DataType< ::minnow::throttle_val >::value();
  }
  static const char* value(const ::minnow::throttle_valResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MINNOW_MESSAGE_THROTTLE_VAL_H
