// Generated by gencpp from file minnow/throttle_valRequest.msg
// DO NOT EDIT!


#ifndef MINNOW_MESSAGE_THROTTLE_VALREQUEST_H
#define MINNOW_MESSAGE_THROTTLE_VALREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace minnow
{
template <class ContainerAllocator>
struct throttle_valRequest_
{
  typedef throttle_valRequest_<ContainerAllocator> Type;

  throttle_valRequest_()
    : val(0.0)  {
    }
  throttle_valRequest_(const ContainerAllocator& _alloc)
    : val(0.0)  {
    }



   typedef float _val_type;
  _val_type val;




  typedef boost::shared_ptr< ::minnow::throttle_valRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::minnow::throttle_valRequest_<ContainerAllocator> const> ConstPtr;

}; // struct throttle_valRequest_

typedef ::minnow::throttle_valRequest_<std::allocator<void> > throttle_valRequest;

typedef boost::shared_ptr< ::minnow::throttle_valRequest > throttle_valRequestPtr;
typedef boost::shared_ptr< ::minnow::throttle_valRequest const> throttle_valRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::minnow::throttle_valRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::minnow::throttle_valRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace minnow

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'minnow': ['/home/monica/panda_work/src/minnow/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::minnow::throttle_valRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::minnow::throttle_valRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::minnow::throttle_valRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::minnow::throttle_valRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::minnow::throttle_valRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::minnow::throttle_valRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::minnow::throttle_valRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c9ee899b5f0899afa6060c9ba611652c";
  }

  static const char* value(const ::minnow::throttle_valRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc9ee899b5f0899afULL;
  static const uint64_t static_value2 = 0xa6060c9ba611652cULL;
};

template<class ContainerAllocator>
struct DataType< ::minnow::throttle_valRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "minnow/throttle_valRequest";
  }

  static const char* value(const ::minnow::throttle_valRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::minnow::throttle_valRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 val\n\
";
  }

  static const char* value(const ::minnow::throttle_valRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::minnow::throttle_valRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.val);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct throttle_valRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::minnow::throttle_valRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::minnow::throttle_valRequest_<ContainerAllocator>& v)
  {
    s << indent << "val: ";
    Printer<float>::stream(s, indent + "  ", v.val);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MINNOW_MESSAGE_THROTTLE_VALREQUEST_H
